### ISSUE TITLE
Validierung mit Profil ipw.ini schlägt fehl

### ISSUE THREAD

**Issue by beistehen** [sogis/ilivalidatorws#8]
Daten im Modell VSA-DSS-Mini werden im Standardprofil geprüft, mit dem Profil `ipw.ini` erscheint jedoch folgender Fehler:
![grafik](https://github.com/sogis/ilivalidatorws/assets/26199857/b500017e-3325-4fe6-ac44-f805ef2ad543)

Es wird keine Möglichkeit angeboten, Logfiles herunterzuladen.

**Comment by edigonzales** [comment]
@beistehen Datei wo?

**Comment by beistehen** [comment]
> @beistehen Datei wo?

via PM

**Comment by edigonzales** [comment]
@beistehen Könnte mir auch vorstellen, dass es mit der Umstellung auf neue MINI-Modell zu tun hat. So als wild guess: https://vsa.ch/models/?dir=organisation

**Comment by edigonzales** [comment]
@beistehen Ja. Prüfe doch mal das neue ilidata.xml vom VSA. Das validiert nicht. Die gleiche Meldung sehe ich auch aufm Serverlog. Das ist aber eine Exception, die ich nicht wirklich gut behandeln kann. Oder nur mit Aufwand.

(Ob die Prüfung mit den Zusatztests überhaupt noch funktioniert mit dem neuen Zeugs, ist noch ne andere Frage).

**Comment by beistehen** [comment]
> Prüfe doch mal das neue ilidata.xml vom VSA. Das validiert nicht.

Ich schaue es mir an. Merci

**Comment by edigonzales** [comment]
Geil, es ist nicht mal wohlgeformtes XML...

**Comment by edigonzales** [comment]
Ah und noch zur Ergänzung. Ich glaube ich lande eben hier: https://github.com/sogis/ilivalidatorws/blob/main/ilivalidatorws-server/src/main/java/ch/so/agi/ilivalidator/controller/ApiController.java#L288 Darum gibts keine Fehlermeldung, weil die Prüfung nicht wirklich zu Ende gebracht werden konnte. Und auch wenn ich den Stacktrace abgreifen könnte, weiss ich nicht, ob das sinnvoll ist. Steht ja vielleicht noch Zeugs drin, dass man nicht sehen sollte.

```
Info: search in repository <https://vsa.ch/models/> for BID <vsa_organisationen>
2023-11-01 12:21:40.721 ERROR 1 --- [pool-2-thread-1] o.jobrunr.server.BackgroundJobPerformer  : Job(id=e1edc626-bb5d-4afb-8b87-4d0718f08641, jobName='Ilivalidator') processing failed: An exception occurred during the performance of the job

java.lang.IllegalArgumentException: Attribute BID missing in basket DatasetIdx16.DataIndex.DatasetMetadata
	at ch.interlis.iom_j.xtf.impl.MyHandler.startElement(MyHandler.java:414) ~[iox-ili-1.21.18.jar:na]
	at ch.interlis.iom_j.xtf.XtfReader.read(XtfReader.java:122) ~[iox-ili-1.21.18.jar:na]
	at ch.interlis.ilirepository.impl.RepositoryAccess.readIliDataXmlLocalFile(RepositoryAccess.java:868) ~[ili2c-tool-5.3.2.jar:na]
	at ch.interlis.ilirepository.impl.RepositoryAccess.readIliDataXml(RepositoryAccess.java:448) ~[ili2c-tool-5.3.2.jar:na]
	at ch.interlis.ilirepository.impl.RepositoryAccess.readIliDataXmlLatest(RepositoryAccess.java:413) ~[ili2c-tool-5.3.2.jar:na]
	at ch.interlis.ilirepository.impl.RepositoryAccess.getIliData(RepositoryAccess.java:146) ~[ili2c-tool-5.3.2.jar:na]
	at ch.interlis.ilirepository.impl.DataFinder.getIliFileMetadataShallow(DataFinder.java:45) ~[ili2c-tool-5.3.2.jar:na]
	at ch.interlis.ilirepository.impl.DataFinder.processRepository(DataFinder.java:21) ~[ili2c-tool-5.3.2.jar:na]
	at ch.interlis.ilirepository.impl.RepositoryVisitor.visitRepositories(RepositoryVisitor.java:153) ~[ili2c-tool-5.3.2.jar:na]
	at ch.interlis.ilirepository.IliManager.getDatasetIndex(IliManager.java:465) ~[ili2c-tool-5.3.2.jar:na]
	at ch.interlis.ilirepository.IliManager.getLocalCopyOfReposFile(IliManager.java:527) ~[ili2c-tool-5.3.2.jar:na]
	at org.interlis2.validator.Validator.validate(Validator.java:249) ~[ilivalidator-1.13.3.jar:na]
	at org.interlis2.validator.Validator.runValidation(Validator.java:79) ~[ilivalidator-1.13.3.jar:na]
	at ch.so.agi.ilivalidator.service.IlivalidatorService.validate(IlivalidatorService.java:206) ~[application.jar:0.0.1-SNAPSHOT]

```

**Comment by beistehen** [comment]
Habs korrigiert und gemeldet. Werde erneut prüfen, sobald ich sehe, dass es angepasst wurde.

**Comment by beistehen** [comment]
Sexy wäre natürlich eine zusätzliche Spalte im Repo Checker, wo der ilivalidator über das jeweilige ilidata.xml laufen gelassen würde...

**Comment by edigonzales** [comment]
> Sexy wäre natürlich eine zusätzliche Spalte im Repo Checker, wo der ilivalidator über das jeweilige ilidata.xml laufen gelassen würde...

Geiler wäre, wenn man die Repo-Inhalte PRÜFEN würde, bevor man sie publiziert... Repo-Checker ist eigentlich komplett überflüssig, wenn die Repo-Anbieter ein Mindestmass an QS hätten.

**Comment by beistehen** [comment]
ilidata.xml wurde im VSA Repository angepasst. Nun funktioniert auch der IWS wieder wie gewünscht.
